# Welcome to Jekyll!
#

# Site settings
title: Paula and Ken
description: Stockholm / Sweden
owner: Paula and Ken # or company name
first_published: 2018 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://paulaandken.us" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
#sass:
#  style: compressed
